[tool.pyright]
typeCheckingMode = "strict"

reportMissingTypeStubs = false
reportUnknownParameterType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownVariableType = false
reportUnknownMemberType = false

executionEnvironments = [
    { root = "."}
]
